<?php

namespace App\Constants;

class BasicUpdateConstants {
	CONST REFERENCE_NO_REQUIRED_CODE                 = 1001;
	CONST CONSIGNMENT_DESCRIPTION_TEXT_REQUIRED_CODE = 1002;
	CONST PURPOSE_OF_IMPORT_TEXT_REQUIRED_CODE       = 1003;
	CONST MODE_OF_TRANSPORT_TEXT_REQUIRED_CODE       = 1004;
	CONST IGM_ARRIVAL_DATE_TEXT_REQUIRED_CODE        = 1005;
	CONST CFS_LOCATION_TEXT_REQUIRED_CODE            = 1006;
	CONST POINT_OF_ENTRY_TEXT_REQUIRED_CODE          = 1007;
	CONST TRANSIT_COUNTRY_TEXT_REQUIRED_CODE         = 1008;


}
